portfolio:
  update_interval_seconds: 900
  concentration_threshold: 0.20

alerts:
  slack_enabled: true
  email_enabled: false
  overnight_only: true
  overnight_hours: "18:00-08:00"

apis:
  alpaca:
    paper_trading: false
  finnhub:
    rate_limit: 60
  polygon:
    rate_limit: 5

theses:
  definitions_file: "src/theses/definitions.json"
